# 06 Numpy.array的合并和分割

In [1]:
import numpy as np

### 合并操作
- concatenate([A, B, C], axis=0) 可将多个array拼接在一起，axis控制拼接的维度
- axis默认是0，即在行的维度进行拼接。相当于新增了几个样本
- axis=1时，即在列的维度进行拼接，相当于新增了几个特征。
- concatenate拼接是需要相同的维度，不同维度会报错，如果不同需要用reshape来转化为相同维度。
- vstack 在垂直的方向上堆叠数据（扩充行），即使维度不同，也可以堆叠在一起
- hstack 在水平的方向上堆叠数据（扩充列）
- 但vstack 和 hstack 一定是要合法的 (2,3) 和(3,) 可以在垂直方向堆叠，而在水平方向无法堆叠。


In [2]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [3]:
x

array([1, 2, 3])

In [4]:
y

array([3, 2, 1])

In [5]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [6]:
z = np.array([666, 666 , 666])

In [7]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [8]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [10]:
# 原来两个样本，三个特征，这样操作相当于再加进两个样本，共四个样本，3个特征
# 加在第0个维度上
# np.concatenate([A, A], axis=0)
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
# 还是两个样本，但需要加入新的三个特征
# 加在第1个维度上
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [14]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions

In [16]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
A2 = np.concatenate([A, z.reshape(1, -1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [19]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [21]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [23]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [25]:
# (2,3) 和(3,) 可以在垂直方向堆叠(vstack)，而在水平方向无法堆叠(hstack)。
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

### 分割操作
- 

In [26]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 方括号设置分割点，两个分割点可切成三段
x1, x2, x3 = np.split(x, [3, 7])

In [29]:
x1

array([0, 1, 2])

In [30]:
x2

array([3, 4, 5, 6])

In [31]:
x3

array([7, 8, 9])