# 08 聚合操作

- np.sum(X) 比python原生的 sum(X) 要快
- np.sum(X),np.max(X),np.min(X) 可以用np开头的方式，其实更推荐，能看出是使用了numpy库
- X.max(), X.min(), X.sum() 也可以使用面向对象的方式来调用  
  
  
- np.sum(X, axis=1),沿着axis=1进行相加，更好的理解的方式是，即这个轴不要了，压缩这个轴（对列进行降维，压成一列），从左右方向压成一块。  
  
  
- np.prod(x)计算所有值的乘积，np.pro(x +1)  
  
   
- np.men(x), np.median(x)

In [1]:
import numpy as np

L = np.random.random(100)

In [3]:
L

array([0.27559367, 0.40276498, 0.1495895 , 0.4132756 , 0.85030566,
       0.27179939, 0.5482504 , 0.39632844, 0.694666  , 0.43730008,
       0.48898452, 0.71286515, 0.17703444, 0.50482839, 0.51860716,
       0.59467387, 0.14708653, 0.61013904, 0.9988405 , 0.56038259,
       0.19989926, 0.83755875, 0.72351721, 0.74212331, 0.55581426,
       0.05214386, 0.59805735, 0.68914571, 0.12055577, 0.96915861,
       0.17034819, 0.99700258, 0.53571315, 0.68891049, 0.45690284,
       0.60100203, 0.41673554, 0.1920164 , 0.38586942, 0.26239946,
       0.35433668, 0.38773537, 0.3229421 , 0.46231049, 0.9177509 ,
       0.96965727, 0.49750617, 0.51954233, 0.13105562, 0.3445847 ,
       0.08009934, 0.16337939, 0.58251533, 0.97430608, 0.17223985,
       0.21333384, 0.98847121, 0.41421853, 0.12394833, 0.38623346,
       0.89272785, 0.05258517, 0.52362495, 0.73252427, 0.87069608,
       0.88528645, 0.19439779, 0.5844859 , 0.61509748, 0.59857774,
       0.62341484, 0.33839587, 0.39146941, 0.06870172, 0.01722

In [4]:
sum(L)

48.94170850611532

In [5]:
np.sum(L)

48.94170850611532

In [9]:
big_array = np.random.rand(1000000)
%time sum(big_array)
%time np.sum(big_array)

Wall time: 216 ms
Wall time: 2.04 ms


499706.14473698783

In [10]:
np.min(big_array)

1.168202344414837e-06

In [11]:
np.max(big_array)

0.9999998035050232

In [13]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.sum(X)

120

In [15]:
# 沿着这个轴，更好的理解的方式是，即这个轴不要了，压缩这个轴，从上下压成一块
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [16]:
# 即axis=1这个轴不要了，压缩这个轴，从左右压成一块
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [17]:
np.prod(X)

0

In [19]:
np.prod(X + 1)

2004189184

In [20]:
np.mean(X)

7.5

In [21]:
np.median(X)

7.5

In [22]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [23]:
np.median(v)

2.0

In [24]:
np.percentile(big_array, q=50)

0.4993542674140173

In [25]:
np.median(big_array)

0.4993542674140173

In [26]:
np.percentile(big_array, q=100)

0.9999998035050232

In [27]:
np.max(big_array)

0.9999998035050232