# 05 Numpy.array 的基本操作

In [1]:
import numpy as np

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 5.1 基本属性
- ndim 返回维度
- shape返回一个tuple，显示矩阵构成
- size 返回大小（即元素的个数）

In [14]:
x.ndim

1

In [15]:
X.ndim

2

In [17]:
x.shape

(10,)

In [18]:
X.shape

(3, 5)

In [19]:
x.size

10

In [20]:
X.size

15

### 5.2 numpy.array 的数据访问
- 一维的访问方式和python自带的array一致
- 多维的访问使用元组作为索引，元组的括号可以省略，例如 X[(2,2)]或者X[2,2]，而不建议用X[2][2]这种方式来进行访问
- numpy.array也支持切片操作,一维 [起始索引:终止索引:步长]
- 切片使用在不同维度上的话，必须使用","操作符，即使用元组做索引的方式
- 使用切片的方式获得的子矩阵是与源矩阵，是以引用的方式相关联的，修改子矩阵会改变源矩阵/修改源矩阵会改变子矩阵
- 创建独立的子矩阵是，使用.copy()。即subX2 = X[:2, :3].copy()

In [22]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[0]

0

In [24]:
x[-1]

9

In [25]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
# 不建议使用
X[0][0]

0

In [28]:
# 建议使用元组作为索引的方式,这里元组的圆括号可以省略
X[(2, 2)]

12

In [30]:
X[2, 2]

12

In [32]:
# 切片
x[0:5]

array([0, 1, 2, 3, 4])

In [35]:
x[5:]

array([5, 6, 7, 8, 9])

In [37]:
# 从头到尾，步长为2
x[::2]

array([0, 2, 4, 6, 8])

In [40]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
# 对多维矩阵也可以进行切片操作
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
# 前两行的前三列
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [43]:
# 使用两个方括号，并不是我们期望的结果
# 第二个方括号是取X[:2]的前三个元素，而只有两个元素，因此结果只有两个元素
# 因此这里的X[:2][:3] 和 X[:2] 结果是不同的
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
# 前两行，间隔为2
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [48]:
# 行倒着数，列倒着数, 即整个矩阵反转
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [49]:
# 获取第一行，多维不推荐
X[0]

array([0, 1, 2, 3, 4])

In [52]:
# 获取第一行，推荐
X[0, :]

array([0, 1, 2, 3, 4])

In [53]:
# 获取第一列
X[:, 0]

array([ 0,  5, 10])

In [54]:
# 子矩阵与源矩阵是引用相连的
subX= X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [55]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [56]:
# 子矩阵变化后，源矩阵也变化了
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [57]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
# 源矩阵变化后，子矩阵也变化了
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [61]:
# 使用.copy()后，子矩阵会独立
subX2 = X[:2, :3].copy()
subX2

array([[0, 1, 2],
       [5, 6, 7]])

In [62]:
subX2[0,0] = 100
subX2

array([[100,   1,   2],
       [  5,   6,   7]])

In [63]:
# 使用.copy()后,子矩阵变化后，源矩阵不再变化
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 5.3 Reshape

- reshape(行数，列数)，转化或改变矩阵的结构，但需要整除
- 一维数组(10,)转化为二维矩阵(1,10),从单方括号会变成双方括号
- 可以用"-1"，来让计算机自动填充行/列数，但一定要能整除，不然会报错。如转换为两列未知行，x.reshape(-1, 2)

In [64]:
x.shape

(10,)

In [65]:
x.ndim

1

In [66]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# 转化为一个2*5的二维数组
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
A.ndim

2

In [74]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
# 结果已经变了，有两个方括号，说明已经是一个矩阵了
# 维度已经改变了，1行10列
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [76]:
# 可见维度已经改变了
B.ndim

2

In [77]:
B.shape

(1, 10)

In [78]:
x.shape

(10,)

In [ ]:
# 只希望有10行，不关心列数
# 或者只希望有2列，不关心几行

In [79]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [80]:
x.reshape(-1, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [81]:
# 10不能被3整除，会报错
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

In [82]:
x.reshape(2, 3)

ValueError: cannot reshape array of size 10 into shape (2,3)