# 08 Aggregation Operation （聚合操作）

### 8.1 聚合统计
- np.sum(X) 比python原生的 sum(X) 要快
- np.sum(X),np.max(X),np.min(X) 可以用np开头的方式，其实更推荐，能看出是使用了numpy库
- X.max(), X.min(), X.sum() 也可以使用面向对象的方式来调用  
  
  
- np.sum(X, axis=1),沿着axis=1进行相加，沿着列的方向，即每一行中的元素进行求合
- 更好的理解的方式是，即这个轴不要了，压缩这个轴（对列进行降维，压成一列），从左右方向压成一块。  
- np.sum(X, axis=0),第0个轴，即行的维度不要了，压缩成一行，从上下方向压成一块。
  
  
- np.prod(x)计算所有值的乘积，np.pro(x +1)  
  
   
- np.men(x), np.median(x) 均值和中位数
- np.percentile(x, q=50) 百分位点，通常考虑q=0,25,50,75,100；0->最小值，50->平均值，100->最大值
- np.var(X), np.std(X) 方差，标准差

In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.54466903, 0.35098438, 0.83685179, 0.87211953, 0.70306734,
       0.72769852, 0.67723156, 0.01143393, 0.39554954, 0.01661382,
       0.98684657, 0.59439437, 0.09032016, 0.08020356, 0.66921875,
       0.90189568, 0.52337737, 0.65711747, 0.36015809, 0.17808554,
       0.0427574 , 0.02848358, 0.90112445, 0.81963198, 0.59479923,
       0.73001444, 0.90788418, 0.44988806, 0.54312456, 0.64322228,
       0.68240175, 0.49052431, 0.59531689, 0.76528741, 0.36656881,
       0.57455059, 0.40276141, 0.9810531 , 0.52289808, 0.52013765,
       0.24964781, 0.37558749, 0.50033897, 0.18453965, 0.90758434,
       0.14379729, 0.03539753, 0.33579006, 0.75380067, 0.6672744 ,
       0.78426802, 0.02258226, 0.81916726, 0.43187028, 0.48014611,
       0.14716364, 0.54753603, 0.66048599, 0.38289364, 0.05737856,
       0.49131456, 0.49531487, 0.33302748, 0.55475821, 0.38395166,
       0.00433405, 0.71856172, 0.34611708, 0.36169886, 0.82096009,
       0.02392956, 0.51602514, 0.60112295, 0.61105822, 0.94280

In [3]:
sum(L)

49.22558144002014

In [4]:
np.sum(L)

49.2255814400201

In [5]:
big_array = np.random.rand(1000000)
%time sum(big_array)
%time np.sum(big_array)

Wall time: 277 ms
Wall time: 2 ms


499723.6512343295

In [6]:
np.min(big_array)

4.439116373378127e-07

In [7]:
np.max(big_array)

0.9999991341059843

In [8]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.sum(X)

120

In [10]:
# 沿着这个轴，更好的理解的方式是，即这个轴不要了，压缩这个轴，从上下压成一块
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [11]:
# 即axis=1这个轴不要了，压缩这个轴，从左右压成一块
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [12]:
np.prod(X)

0

In [13]:
np.prod(X + 1)

2004189184

In [14]:
np.mean(X)

7.5

In [15]:
np.median(X)

7.5

In [16]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [17]:
np.median(v)

2.0

In [18]:
np.percentile(big_array, q=50)

0.4995751655990268

In [19]:
np.median(big_array)

0.4995751655990268

In [20]:
np.percentile(big_array, q=100)

0.9999991341059843

In [21]:
np.max(big_array)

0.9999991341059843

In [22]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array, q=percent))

4.439116373378127e-07
0.25011898848158
0.4995751655990268
0.7494674022167922
0.9999991341059843


In [23]:
np.var(big_array)

0.08324466826682135

In [24]:
np.std(big_array)

0.28852152132349046

In [25]:
# 生成一个正太分布的数组，均值为0，标准差为1
x =np.random.normal(0, 1, size=1000000)

In [26]:
np.mean(x)

0.001071169063334824

In [27]:
np.std(x)

1.00049733902485