# 09 Arg Operation （索引操作/sort/partition）

### 9.1 索引
- np.argmin(X) 获取最小值的索引
- np.argmax(X) 获取最大值的索引

In [1]:
import numpy as np
# 生成一个正太分布的数组，均值为0，标准差为1
x =np.random.normal(0, 1, size=1000000)
# 生成一个随机二维数组，有4行n列，共16个值
X = np.arange(16).reshape(4, -1)

In [2]:
np.min(x)

-4.893247575673578

In [3]:
np.argmin(x)

338023

In [4]:
x[656023]

-0.36502025398826143

In [5]:
np.argmax(x)

875781

In [6]:
x[888384]

0.33927859223294454

In [7]:
np.max(x)

4.649653049993063

### 9.2 排序和使用索引
- np.random.shuffle(x) 乱序
- np.sort(x) 这个操作是不对x进行更改的，只是生成一个排好序的数组
- x.sort() 而使用面向对象的方式排序，将会对x进行改动。  
- np.argsort(x)  以索引的形式返回排序后的结果  
  
  
- np.partition(x, 标定点的值) 
    - 快速排序中partition处理，即选定一个标定点(这里是3)
    - 标定点前面的元素都比小于等于标定点，后面的元素都比标定点大
    - 但无论是标定点前还是后，都是无序的。
- np.argpartition(x, 3)  以索引的形式返回partition后的结果
  
  
- np.sort(X, axis=1)  默认axis=1，即沿着列的方向，每一行进行排序
- np.sort(X, axis=0)  与np.sum的逻辑一样  
- np.sort(X, axis=1)
- np.argpartition(X, 2, axis=1)

In [8]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
# 乱序
np.random.shuffle(x)
x

array([13,  0,  4, 12,  7, 14,  8,  1,  5,  9,  3, 15, 10, 11,  2,  6])

In [10]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
x

array([13,  0,  4, 12,  7, 14,  8,  1,  5,  9,  3, 15, 10, 11,  2,  6])

In [12]:
x.sort()

In [13]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
X = np.random.randint(10, size=(4,4))
X

array([[4, 1, 7, 2],
       [2, 8, 0, 1],
       [6, 8, 1, 6],
       [2, 6, 6, 1]])

In [15]:
# 默认的axis为1，即沿着列的方向，每一行进行排序
np.sort(X)

array([[1, 2, 4, 7],
       [0, 1, 2, 8],
       [1, 6, 6, 8],
       [1, 2, 6, 6]])

In [16]:
np.sort(X, axis=1)

array([[1, 2, 4, 7],
       [0, 1, 2, 8],
       [1, 6, 6, 8],
       [1, 2, 6, 6]])

In [17]:
np.sort(X, axis=0)

array([[2, 1, 0, 1],
       [2, 6, 1, 1],
       [4, 8, 6, 2],
       [6, 8, 7, 6]])

In [18]:
# 排序中的索引
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.random.shuffle(x)
x

array([ 6,  7, 15, 14,  2,  9,  8, 10, 13,  4, 11, 12,  0,  1,  5,  3])

In [20]:
# 按索引排列的顺序，第一小的引是11，第二小的索引是9
np.argsort(x)

array([12, 13,  4, 15,  9, 14,  0,  1,  6,  5,  7, 10, 11,  8,  3,  2],
      dtype=int64)

In [21]:
# 快速排序中partition处理，即选定一个标定点(这里是3)
# 标定点前面的元素都比小于等于标定点，后面的元素都比标定点大
# 但无论是标定点前还是后，都是无序的。
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7, 13,  8, 11, 12,  9, 14, 15, 10])

In [22]:
# 把partition后的数组的索引获取出来
np.argpartition(x, 3)
#array  2,  1, 0,  3,  5,   4,  6, 7。。。。

array([12, 13,  4, 15,  9, 14,  0,  1,  8,  6, 10, 11,  5,  3,  2,  7],
      dtype=int64)

In [23]:
X

array([[4, 1, 7, 2],
       [2, 8, 0, 1],
       [6, 8, 1, 6],
       [2, 6, 6, 1]])

In [24]:
np.argsort(X, axis=1)

array([[1, 3, 0, 2],
       [2, 3, 0, 1],
       [2, 0, 3, 1],
       [3, 0, 1, 2]], dtype=int64)

In [25]:
# 与一维数据一致
np.argpartition(X, 2, axis=1)

array([[1, 3, 0, 2],
       [2, 3, 0, 1],
       [2, 0, 3, 1],
       [3, 0, 2, 1]], dtype=int64)

In [26]:
np.argpartition(X, 2, axis=0)

array([[1, 0, 1, 1],
       [3, 3, 2, 3],
       [0, 2, 3, 0],
       [2, 1, 0, 2]], dtype=int64)