# 03 numpy.array 基础

## 3.1 Python List 的特点
- python的list其实是对类型不做限定的list的
- 每个list里的每一个元素的类型是可以不一样的
- 非常灵活，赋值和存储比较方便
- 但效率非常低，因为要检查每个元素的类型 

In [7]:
L = [i for i in range(10)]

In [8]:
L[5]

5

In [10]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [13]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

## 3.2Python Array
- array只能存储一种类型的元素
- ‘i’代表整型的数据
- 降低了灵活性，但效率提高了
- 只是将存储的数据当作数组或者二维数组来看，而不能当作向量/矩阵来看
- 没有配备向量/矩阵相关的运算

In [14]:
import array

In [15]:
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [17]:
arr[5] = 'Machine Learning'
arr

TypeError: an integer is required (got type str)

## 3.3numpy.array
- 也只能存储一种类型的数据
- 能进行向量/矩阵相关的运算
- 会自动进行类型转化，如果array.dtyp是整型int类型，5.0会转换为5，3.14转换为3
- 而如果在定义array时，有浮点数类型的元素，array.dtype将会为float类型。

In [2]:
import numpy

In [4]:
numpy.__version__

'1.19.2'

In [5]:
import numpy as np

In [6]:
np.__version__

'1.19.2'

In [18]:
nparr = np.array([i for i in range(10)])

In [19]:
nparr[5]

5

In [20]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [21]:
nparr[5] = 'Machine Learning'

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [22]:
nparr.dtype

dtype('int32')

In [23]:
nparr[5] = 5.0

In [26]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
nparr.dtype

dtype('int32')

In [28]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
nparr.dtype

dtype('int32')

In [33]:
nparr2 = np.array([1, 2, 3.14])

In [34]:
nparr2

array([1.  , 2.  , 3.14])

In [36]:
nparr2.dtype

dtype('float64')