# 07 numpy.array中的运算

### 7.1 python3原生列表和numpy.array生成的比较
给定一个向量，让向量中每一个数乘以2  
a = (0,1,2)  
a*2 = (0,2,4)

- python原生的列表不支持对元素直接计算
- python原生：列表生成式 快于 for循环生成
- numpy支持生成式语法
- numpy生成式 快于 python原生列表生成式
- numpy支持向量和矩阵的运算。把数组看作向量和矩阵，且速度非常快

In [2]:
n = 10
L = [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# python 原生的列表不支持对元素直接计算
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
A = []
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
n = 1000000
L = [i for i in range(n)]

In [16]:
## 原生for循环生成列表较慢
%%time
A = []
for e in L:
    A.append(2*e)

Wall time: 139 ms


In [17]:
n = 1000000
L = [i for i in range(n)]

In [18]:
## 原生列表生成式速度有提升
%%time
A = [2*e for e in L]

Wall time: 88.5 ms


In [19]:
import numpy as np

In [20]:
L = np.arange(n)

In [21]:
## numpy中也支持生成式的语法，而且速度更快
%%time
A = np.array(2*e for e in L)

Wall time: 16 ms


In [22]:
%%time
A = 2 * L

Wall time: 5.03 ms


In [23]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [24]:
n = 10
L = np.arange(10)
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 7.2 Universal Functions

In [44]:
# +，-，*，**，/，//，%
# np.abs(X)，np.sin(X)，np.cos(X)，np.tan(X)
# np.exp(X)，np.power(3,X)，np.log(X)，np.log2(X)，np.log10(X)

In [25]:
X = np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [27]:
X - 1 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [29]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [30]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [31]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [32]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [33]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [34]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [36]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [37]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [38]:
# e^x
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [39]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [40]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [41]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [42]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 7.3 矩阵与矩阵运算

- '+','-'是一致的  
- '*' 和 '/'是矩阵对应元素乘除的结果，不是标准的矩阵的乘法  
- 矩阵乘法的定义[A矩阵的每一行与B矩阵的每一列进行相乘再相加] 
- 标准的矩阵乘法的应使用 A.dot(B)   
- 矩阵的转置 A.T

In [46]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [47]:
B = np.full((2,2), 10)
B

array([[10, 10],
       [10, 10]])

In [48]:
A + B

array([[10, 11],
       [12, 13]])

In [49]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [50]:
# A 和 B 对应元素相乘的结果，不是标准的矩阵乘法
A * B

array([[ 0, 10],
       [20, 30]])

In [52]:
# A 和 B 对应元素相除的结果，不是标准的矩阵除法
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [54]:
# 标准的矩阵乘法 结果的 Xij 为A的第i行和B的第j列相乘后再相加的值
A.dot(B)

array([[10, 10],
       [50, 50]])

In [55]:
A.T

array([[0, 2],
       [1, 3]])

In [57]:
C = np.full((3,3), 666)
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [58]:
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [59]:
A.dot(C)

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

### 7.4 向量和矩阵的运算

- 数学上向量和矩阵的加法是没有意义的
- numpy中自动将低维的元素和高维元素中的减去一位的每一位元素做加法
- 类似于数和一个向量做加法，即数和每个元素做加法
- 可以理解为和对应位置的元素做加法，即向量与每一行做加法
- 转化成数学意义上的，可以将向量v堆叠成和A一样高的矩阵，再进行加法
- 更自由的向量堆叠 np.tile(v , (行堆叠次数, 列堆叠次数))  
  
  
- 只要熟悉numpy的运算规则，v + A的使用是非常自然的
- v*A的结果也是向量与每一行做乘法，而且也是对应元素进行相乘
- 向量和矩阵的乘法使用 v.dot(A)。
- A.dot(v)数学上是不成立的，但numpy自动把v转换为了列向量即(2,1)的矩阵，然后进行计算。


In [61]:
v = np.array([1,2])
v

array([1, 2])

In [62]:
A

array([[0, 1],
       [2, 3]])

In [63]:
v + A

array([[1, 3],
       [3, 5]])

In [65]:
# 要按
# 手动将v堆叠成A的高度（A的行数），这里堆叠了2次
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [67]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [70]:
# 手动设置堆叠的维数
np.tile(v , (2, 1))

array([[1, 2],
       [1, 2]])

### 7.5 矩阵的逆

- 不管左乘还是又乘，逆矩阵与矩阵相乘会得到单位矩阵
- 并不是所有的矩阵都有逆矩阵，至少是一个方针才行
- invA = np.linalg.inv(A)  
  

- 无法求逆矩阵，可以转而求伪逆矩阵
- 原矩阵和伪逆矩阵相乘也是单位矩阵，但是反过来乘则不行
- pinvA = np.linalg.pinv(A)


In [71]:
A

array([[0, 1],
       [2, 3]])

In [72]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [73]:
invA = np.linalg.inv(A)

In [74]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [75]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [85]:
 X = np.arange(16).reshape((2,8))

In [86]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [87]:
# 不是方阵无法就求逆矩阵
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [89]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -5.20417043e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [91]:
pinvX.shape

(8, 2)

In [92]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 6.66133815e-16,  1.00000000e+00]])

In [94]:
pinvX.dot(X)

array([[ 4.16666667e-01,  3.33333333e-01,  2.50000000e-01,
         1.66666667e-01,  8.33333333e-02, -1.66533454e-16,
        -8.33333333e-02, -1.66666667e-01],
       [ 3.33333333e-01,  2.73809524e-01,  2.14285714e-01,
         1.54761905e-01,  9.52380952e-02,  3.57142857e-02,
        -2.38095238e-02, -8.33333333e-02],
       [ 2.50000000e-01,  2.14285714e-01,  1.78571429e-01,
         1.42857143e-01,  1.07142857e-01,  7.14285714e-02,
         3.57142857e-02, -1.56125113e-16],
       [ 1.66666667e-01,  1.54761905e-01,  1.42857143e-01,
         1.30952381e-01,  1.19047619e-01,  1.07142857e-01,
         9.52380952e-02,  8.33333333e-02],
       [ 8.33333333e-02,  9.52380952e-02,  1.07142857e-01,
         1.19047619e-01,  1.30952381e-01,  1.42857143e-01,
         1.54761905e-01,  1.66666667e-01],
       [-4.16333634e-17,  3.57142857e-02,  7.14285714e-02,
         1.07142857e-01,  1.42857143e-01,  1.78571429e-01,
         2.14285714e-01,  2.50000000e-01],
       [-8.33333333e-02, -2.380952